# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Reading Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PureLayout'
	
  target 'Reading TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Reading TrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
